# Generated by Django 3.1.2 on 2020-10-23 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0002_savesessionauthusers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savesessionauthusers',
            name='session_data',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
