# Generated by Django 3.1.2 on 2020-11-23 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0004_auto_20201026_1050'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='savesessionauthusers',
            options={'verbose_name': 'Результат', 'verbose_name_plural': 'Результаты'},
        ),
    ]
